version: '3.9'
services:
  api:
    build: .
    container_name: wallet_api
    hostname: wallet_api
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www
    networks:
      - wallet
  mongodb:
    image: mongo:4.2
    container_name: wallet_db
    hostname: wallet_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: wallet
      MONGO_INITDB_ROOT_PASSWORD: wallet
    networks:
      - wallet
networks:
  wallet:
    name: wallet
    driver: bridge
